# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[character]
# success_symbol = "[âœ](bold green)"
success_symbol = "ğŸŒ"
error_symbol = '[âœ—](bold red)'

[package]
disabled = true

[azure]
disabled = true
style = 'blue'

[kubernetes]
disabled = false
style = 'cyan bold'
symbol='â˜¸ï¸ '